Repository kimdovi-dev/Airtravel999, pull requests merged in 2021-11, with the labels that each got.

#6 Task 5
  backend/.gitignore
  backend/app.py
  frontend/src/index.html
Labels: task

#8 Chore/1
  assets/main.css
  assets/reset.css
  assets/styled.css
Labels: UI, task

#10 make route
  backend/__pycache__/app1.cpython-39.pyc
  backend/__pycache__/auth.cpython-39.pyc
  backend/__pycache__/like.cpython-39.pyc
  backend/__pycache__/test.cpython-39.pyc
  backend/__pycache__/tour.cpython-39.pyc
  backend/app.py
  backend/auth.py
  backend/like.py
  backend/tour.py
Labels: task

#13 chore/12:메인페이지 수정 1차
  frontend/src/assets/images/img1.jpg
  frontend/src/assets/images/img2.jpg
  frontend/src/assets/images/img3.jpg
  frontend/src/assets/images/img4.jpg
  frontend/src/assets/images/img5.jpg
  frontend/src/assets/images/img6.jpg
  frontend/src/assets/images/img7.jpg
  frontend/src/assets/main.css
  frontend/src/index.html
Labels: UI, task

#14 Chore/9
  frontend/src/assets/modal.css
  frontend/src/assets/reset.css
  frontend/src/modal.html
Labels: UI, task

#17 Chore/16
  frontend/src/assets/modal.css
  frontend/src/assets/reset.css
  frontend/src/modal.html
Labels: UI, feature

#19 chore (#18): 게시물 생성 모달 추가
  frontend/src/assets/modal.css
  frontend/src/modal.html
Labels: UI, feature

#20 Chore/15 메인페이지 수정 4차
  frontend/src/assets/images/container.png
  frontend/src/assets/images/logo.png
  frontend/src/assets/main.css
  frontend/src/index.html
Labels: UI, task

#24 make tour api and add gitignore
  backend/.gitignore
  backend/__pycache__/app1.cpython-39.pyc
  backend/__pycache__/auth.cpython-39.pyc
  backend/__pycache__/like.cpython-39.pyc
  backend/__pycache__/test.cpython-39.pyc
  backend/__pycache__/tour.cpython-39.pyc
  backend/app.py
  backend/tour.py
Labels: feature, task

#25 Chore/22
  frontend/src/assets/images/@img-post1.jpg
  frontend/src/assets/images/@img-post2.jpg
  frontend/src/assets/images/@img-post3.jpg
  frontend/src/assets/images/@img-visual1.jpg
  frontend/src/assets/mypage.css
  frontend/src/assets/styled.css
  frontend/src/mypage.html
Labels: UI

#30 make like api
  backend/like.py
  backend/tour.py
Labels: feature, task

#32 tour with authentication complete
  backend/auth.py
  backend/tour.py
Labels: feature, task

#33 feature (#28): form 필수 입력 사항 체크
  frontend/src/assets/modal.css
  frontend/src/modal.html
  frontend/src/mypage.html
Labels: UI, feature

#36 make config file and connect remote server
  backend/.gitignore
  backend/auth.py
  backend/config.py
  backend/like.py
  backend/tour.py
Labels: feature, task

#38 Chore/15
  frontend/src/assets/modal.css
  frontend/src/mypage.html
Labels: UI, feature, task

#39 메인페이지 수정 5차(test)
  frontend/src/mypage.html
Labels: UI, feature, task

#40 메인페이지 수정 5차
  frontend/src/index.html
  frontend/src/mypage.html
Labels: UI, feature, task

#41 feature (#34): 첨부된 파일 표시 벳지 삭제 기능 추가
  frontend/src/assets/js/jquery-3.6.0.min.js
  frontend/src/assets/modal.css
  frontend/src/modal.html
Labels: UI, feature

#43 jinja template complete
  backend/app.py
  backend/auth.py
  backend/static/images/@img-post1.jpg
  backend/static/images/@img-post2.jpg
  backend/static/images/@img-post3.jpg
  backend/static/images/@img-visual1.jpg
  backend/static/images/container.png
  backend/static/images/img1.jpg
  backend/static/images/img2.jpg
  backend/static/images/img3.jpg
  backend/static/images/img4.jpg
  backend/static/images/img5.jpg
  backend/static/images/img6.jpg
  backend/static/images/img7.jpg
  backend/static/images/logo.png
  backend/static/js/jquery-3.6.0.min.js
  backend/static/main.css
  backend/static/modal.css
  backend/static/mypage.css
  backend/static/reset.css
  backend/static/styled.css
  backend/templates/index.html
  backend/templates/modal.html
  backend/templates/mypage.html
Labels: feature, task

#46 bugfix (#42): 파일 선택 안하고 탐색기 종료했을 경우 빈 뱃지 생성되는 오류 수정
  frontend/src/assets/modal.css
  frontend/src/modal.html
Labels: bug, UI, feature

#49 Chore/15
  frontend/src/assets/fontawesome.css
  frontend/src/assets/main.css
  frontend/src/assets/mypage.css
  frontend/src/assets/styled.css
  frontend/src/index.html
  frontend/src/mypage.html
Labels: UI, feature, task

#50 Chore (#47): 메인페이지 UI 추가 작업 1차
  .gitignore
  frontend/src/assets/images/@ico-arrow-top.png
  frontend/src/assets/main.css
  frontend/src/assets/modal.css
  frontend/src/index.html
Labels: UI, feature

#51 edit like api and add mytour api
  backend/auth.py
  backend/like.py
  backend/tour.py
Labels: feature, task

#54 download jquery cookie module & import jquery, jquery cookie module to all html file
  backend/static/js/jquery.cookie.js
  backend/templates/index.html
  backend/templates/modal.html
  backend/templates/mypage.html
Labels: task

#59 로그인 후 index.html 헤더에 로그인, 로그아웃 버튼 사라지게 세팅 & app.py home function 수정
  backend/app.py
  backend/templates/index.html
Labels: feature, task

#61 로그아웃 버튼 클릭시 쿠키 삭제 로직 추가
  backend/templates/index.html
Labels: feature

#63 chore (#52): main 페이지 UI 스타일 추가 1차
  frontend/src/assets/images/@img-visual2.jpg
  frontend/src/assets/images/@img-visual3.jpg
  frontend/src/assets/js/front_ui.js
  frontend/src/assets/main.css
  frontend/src/assets/mypage.css
  frontend/src/index.html
  frontend/src/mypage.html
  frontend/src/slider.html
Labels: enhancement, UI

#67 Implement card filter by continent
  backend/app.py
  backend/auth.py
  backend/static/fontawesome.css
  backend/static/images/@ico-arrow-top.png
  backend/static/images/@img-visual2.jpg
  backend/static/images/@img-visual3.jpg
  backend/static/js/front_ui.js
  backend/static/main.css
  backend/static/modal.css
  backend/static/mypage.css
  backend/static/styled.css
  backend/templates/index.html
  backend/tour.py
Labels: feature, task

#68 task (#66): 스크립트 파일 수정 및 정리
  frontend/src/assets/js/front_ui.js
Labels: feature, task

#73 connect mytour page jinja template
  backend/app.py
  backend/static/fontawesome.css
  backend/static/main.css
  backend/static/modal.css
  backend/static/mypage.css
  backend/static/styled.css
  backend/templates/index.html
  backend/templates/mypage.html
  backend/tour.py
Labels: feature, task

#76 chore (#71): 게시글 생성 모달 수정
  frontend/src/assets/doeun.css
  frontend/src/assets/js/front_ui.js
  frontend/src/assets/styled.css
  frontend/src/modal.html
Labels: UI

#78 chore (#77): 게시물 추가 팝업 위치 조정 및 코드 정리
  frontend/src/assets/doeun.css
  frontend/src/assets/js/front_ui.js
  frontend/src/mypage copy.html
Labels: bug, task

#79 implement sign up
  backend/auth.py
  backend/templates/index.html
  backend/templates/mypage.html
  backend/tour.py
Labels: feature, task

#80 task (#71): 스타일 주석 추가
  frontend/src/assets/doeun.css
  frontend/src/assets/modal.css
  frontend/src/mypage copy.html
  frontend/src/mypage.html
Labels: task

#84 chore (#81): 게시물 보기 모달창 추가
  frontend/src/assets/doeun.css
  frontend/src/assets/js/front_ui.js
  frontend/src/index.html
  frontend/src/modal.html
  frontend/src/mypage copy.html
Labels: UI, feature, task

#86 Chore/15
  frontend/src/assets/main.css
Labels: UI, feature, task

#87 chore (#69): 스크롤바 스타일 추가, 스크롤탑 버튼 아이콘 변경
  frontend/src/assets/doeun.css
  frontend/src/assets/main.css
  frontend/src/index.html
  frontend/src/mypage copy.html
Labels: UI, task

#88 index.html card like 버튼 추가 & hover 시 색변경 기능 추가
  backend/templates/index.html
Labels: UI, feature

#93 bugfix (#85): UI 버그 수정
  frontend/src/assets/doeun.css
  frontend/src/assets/js/front_ui.js
  frontend/src/index.html
  frontend/src/mypage copy.html
Labels: bug, UI, task

#96 create tour card
  backend/static/doeun.css
  backend/static/js/front_ui.js
  backend/static/main.css
  backend/static/modal.css
  backend/static/styled.css
  backend/templates/mypage.html
  backend/tour.py
Labels: feature, task

#98 Hotfix/modla js
  frontend/src/assets/images/favicon.png
  frontend/src/assets/js/front_ui.js
  frontend/src/mypage copy.html
Labels: feature, task

#100 index.html 사용자 like 기능 ajax 구현 (좋아요, 좋아요 취소)
  backend/app.py
  backend/like.py
  backend/templates/index.html
Labels: feature

#106 bugfix (#105): 가장 첫 게시물만 팝업이 뜨는 오류 수정
  frontend/src/assets/js/front_ui.js
Labels: bug, feature

#110 bug fix
  backend/static/doeun.css
  backend/static/js/front_ui.js
  backend/static/modal.css
  backend/templates/index.html
  backend/templates/mypage.html
Labels: feature, task

#113 bug fix
  backend/static/js/front_ui.js
  backend/templates/index.html
  backend/templates/mypage.html
  backend/tour.py
Labels: bug

#116 my page goHome function
  backend/templates/index.html
  backend/templates/mypage.html
  backend/tour.py
Labels: feature, task
